#!/bin/bash
# This script suppose to generate db and objects (I will add validation later)
# author: Anatoly Spektor
# 
# Need to be done:
#  - create collections for each table
#  - make sure mogno is installed before doing "mongo" (using rpm)
#  - drop db and collection and than recreate
#  - put more dummy values

setup_dir=`pwd`

#Fine distribution and install Mongo depending on distro
distro=$(cat /etc/*-release |  grep "^ID=" | awk -F'=' '{print $2}')
arch=$(uname -m)
clear
if [[ "$distro" = "fedora" ]]
 then	
	#Installing Mongo Dependencies (like git)
	echo "Installing dependencies.."
	sudo yum -y install git-core scons gcc-c++ glibc-devel

elif [[ $distro = "ubuntu" ]]
 then
	#Installing Mongo Dependencies (like git)
	echo "Installing dependencies.."
	sudo apt-get install git-core build-essential scons
else
	echo "At This point LinuxLock supports only Fedora and Ubuntu, please email to support@linuxlock.com to get more information" 2> /dev/null 
	exit 134
fi

mkdir ~/LinuxLock >/dev/null 2>&1; cd ~/LinuxLock >/dev/null 2>&1

type mongo  >/dev/null 2>&1
if [[ $? != 0 ]]
 then 
	git clone git://github.com/mongodb/mongo.git; 
	cd mongo; git checkout r2.4.0; 
	scons all;
 else 
	echo "Good news! You already have mongo installed! [skipping installation]";
fi

type node >/dev/null 2>&1
if [[ $? != 0 ]]
 then 
	git clone git://github.com/joyent/node.git;
	cd node; ./configure;make; 
	sudo make install
 else 
	echo "Good news! You already have Node installed! [skipping installation]";
fi

echo "Populating Mongo Database with required collections..."
cd $setup_dir
chmod 775 mongo_setup;
chmod 775 mongo_test;
mongo < ./mongo_setup | ./mongo_test


echo "Succesfull installation of Node, Mongo and all dependencies required for Linux Lock!"